### ISSUE TITLE
composer install of Vardot / varbase version 9.0.4 fails on 'DrupalFinder\DrupalFinder' not found

### ISSUE THREAD

**Issue by 3pleo** [Vardot/varbase#100]
Trying to install with 
` composer create-project Vardot/varbase-project:~9.0.3 YOUR_PROJECT --no-dev --no-interaction `

which as expected loads 9.0.4 fails with:
` PHP Fatal error:  Uncaught Error: Class 'DrupalFinder\DrupalFinder' not found in /<path_to_project_name>/docroot/profiles/varbase/src/composer/ScriptHandler.php:26 `

The packagist composer.json seems to be missing following dependencies which were in 9.0.3
`     "webflo/drupal-finder": "~1.0",`
`    "webmozart/path-util": "~2.0", `

Please help.

**Comment by Natshah** [comment]
Removed webmozart/path-util and webflo/drupal-finder from vardot/varbase-project #128

**Comment by 3pleo** [comment]
Thanks for your quick response.

I'm using Composer version 2.2.4  on Ubuntu 20.04.

See full error stack below:
`PHP Fatal error:  Uncaught Error: Class 'DrupalFinder\DrupalFinder' not found in /<path-to-project-name>/docroot/profiles/varbase/src/composer/ScriptHandler.php:26
Stack trace:
#0 /<path-to-project-name>/docroot/profiles/varbase/src/composer/ScriptHandler.php(143): Varbase\composer\ScriptHandler::getDrupalRoot()
#1 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(389): Varbase\composer\ScriptHandler::postDrupalScaffoldProcedure()
#2 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(238): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
#3 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(104): Composer\EventDispatcher\EventDispatcher->doDispatch()
#4 /<path-to-project-name>/vendor/drupal/core-composer-scaffold/Handler.php(182): Composer\EventDispatcher\EventDispatcher->dispatch()
#5 /<path-to-project-name>/vendor/drupal/core-composer-scaffold/Plugin.php(102): Drupal\Composer\Plugin\Scaffold\Handler->scaffold()
#6 [internal function]: Drupal\Composer\Plugin\S in /<path-to-project-name>/docroot/profiles/varbase/src/composer/ScriptHandler.php on line 26
`

**Comment by Natshah** [comment]
Thanks for reporting :) :+1: 
Only having the **webflo/drupal-finder** in the **vardot/varbase-project** template
You need to add **drush** 

Are you building with 
```
composer create-project Vardot/varbase-project:~9.0.0 PROJECT_DIR_NAME --no-dev --no-interaction
```
or with
```
composer create-project Vardot/varbase-project:~9.0.0 PROJECT_DIR_NAME --stability dev --no-interaction
```

Adding **webflo/drupal-finder** back into the **vardot/varbase-project** template

**Comment by Natshah** [comment]
Releasing a quick fix release in 10 minutes to be able to use
```
composer create-project Vardot/varbase-project:~9.0.0 PROJECT_DIR_NAME --no-dev --no-interaction
```

**Comment by Natshah** [comment]
Have webflo/drupal-finder back in vardot/varbase-project to be able to build projects with --no-dev --no-interaction flag arguments in the composer create-project command [#130](https://github.com/Vardot/varbase-project/issues/130)

**Comment by 3pleo** [comment]
Excellent! It works perfectly now with:

`composer create-project Vardot/varbase-project:~9.0.0 PROJECT_DIR_NAME --no-dev --no-interaction`

Thanks a million.

**Comment by Natshah** [comment]
Fixed and a quick fix release only on the **vardot/varbase-project** template
**[9.0.4.1](https://packagist.org/packages/vardot/varbase-project#9.0.4.1)**

Now it works with --no-dev or with dev

```
composer create-project Vardot/varbase-project:~9.0.0 test_varbase_with_no_dev_build --no-dev --no-interaction
```
and 
```
composer create-project Vardot/varbase-project:~9.0.0 test_varbase_with_dev_build --stability dev --no-interaction
```
