### ISSUE TITLE
Issues installing Varbase version 9.0.3 and 9.0.4.1 with Drush version 10.6.2 and Drush version 11.0.2

### ISSUE THREAD

**Issue by 3pleo** [Vardot/varbase#102]
While trying to install both versions 9.0.3 and 9.0.4 with drush 10.6.2 on Ubuntu 20.04.3,
Installation with drush 10.6.2 failed with 
`
[error]  Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in GuzzleHttp\choose_handler() (line 61 of $COMPOSER_HOME/vendor/guzzlehttp/guzzle/src/functions.php) #0 <path-to-my-project>/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(1130): GuzzleHttp\HandlerStack::create()
#2 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(1267): Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#3 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(1213): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#4 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(1115): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#5 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(618): Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#6 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(1265): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#7 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(1119): Symfony\Component\DependencyInjection\ContainerBuilder->doResolveServices()
#8 <path-to-my-project>/vendor/symfony/dependency-injection/ContainerBuilder.php(618): Symfony\Component\DependencyInjection\ContainerBuilder->createService()
`

To resolve this problem "**temporarily**" override vendor/guzzlehttp with composer version of guzzlehttp
`
cp -r ~/.config/composer/vendor/guzzlehttp  <path-to-my-project>/vendor/
`

**Then installation with drush completed successfully,**
**But when tried to browse to url, got the following error:**
`
The website encountered an unexpected error. Please try again later.
Error: Interface 'Psr\Http\Client\ClientInterface' not found in include() (line 17 of <path-to-my-project>/vendor/guzzlehttp/guzzle/src/Client.php).
`

**To resolve the problem, I copied the version downloaded with varbase back. And the site now works**

**What could be missing in the guzzlehttp version required by varbase? ?**

### Problem Installing with drush 11.0.2
Installation with drush 11.0.2 failed with
`
PHP Fatal error:  Access level to DrupalCodeGenerator\Command\Generator::getDestination() must be public (as in class DrupalCodeGenerator\Command\GeneratorInterface) in ~/.config/composer/vendor/chi-teck/drupal-code-generator/src/Command/Generator.php on line 362
 [warning] Drush command terminated abnormally.
`

Please help for the benefit of others and improved experience of the good varbase distro.

Regards

**Comment by Natshah** [comment]
Thanks for reporting :)

**Drush 11.0.0** stable was released **2022-01-11**
https://github.com/drush-ops/drush/releases/tag/11.0.0

**Drush 11.0.1** was released **2022-01-17**
https://github.com/drush-ops/drush/releases/tag/11.0.1

Working on that at 
**[Issue #3259112: Update Drush from ~10.0 to ~11.0](https://www.drupal.org/project/varbase/issues/3259112)**

**Comment by Natshah** [comment]
Released **Varbase 9.0.5**
https://www.drupal.org/project/varbase/releases/9.0.5
Please, have a look at the released issues and documentation for how to switch to use **Drush ~11.0**
