### ISSUE TITLE
We cannot include Vardot as hardcoded. Let's tokenize this.

### ISSUE THREAD

**Issue by moerazem** [Vardot/varbase#70]
https://github.com/Vardot/varbase/blob/199a96a9b0bd5256139dbb580904ca125e0275a0/modules/varbase_features/varbase_seo/config/install/metatag.metatag_defaults.global.yml#L27

**Comment by Natshah** [comment]
Noted

**Comment by Natshah** [comment]
Fixed at:
**Changed [Varbase SEO] feature module: Reset for a use of a general generator and publisher for the HTML pages**
https://www.drupal.org/node/2916352
