### ISSUE TITLE
Composer project creation fails 8.x-5x branch (as per README.md instructions)

### ISSUE THREAD

**Issue by Doomd** [Vardot/varbase#80]
The README.md for the 8.x-5x branch has instructions for installing the project via composer:

> To install the most recent stable release of Varbase 8.5.x run this command:
 `composer create-project Vardot/varbase-project:^8.5.0-alpha1 PROJECT_DIR_NAME --no-interaction
`

This results in the following response:
```
 [InvalidArgumentException]
  Could not find package vardot/varbase-project with version ^8.5.0-alpha1.
```

**Comment by Natshah** [comment]
We did not 8.5.0-alpha1. 
It's only under development

**Comment by Natshah** [comment]
We have made a change to the README.md file does not miss lead other developers.
We will have it back when we release the 8.5.0-alpha1
