### ISSUE TITLE
Change "docroot" to "public_html"

### ISSUE THREAD

**Issue by gordasgdc** [Vardot/varbase#81]
Hello 
How can i change the "docroot" name ?

**Comment by Natshah** [comment]
Project template for Varbase distribution
https://github.com/Vardot/varbase-project

https://github.com/Vardot/varbase-project/blob/8.4.x/composer.json

for Varbase 8.4.18
https://github.com/Vardot/varbase-project/blob/8.4.18/composer.json

You could copy the composer.json file into a new folder in your local development or testing computer.

change docroot to what you like
```
    "installer-paths": {
      "docroot/core": ["drupal/core"],
      "docroot/profiles/{$name}": ["type:drupal-profile"],
      "docroot/modules/contrib/{$name}": ["type:drupal-module"],
      "docroot/themes/contrib/{$name}": ["type:drupal-theme"],
      "docroot/libraries/{$name}": ["type:drupal-library"],
      "docroot/modules/custom/{$name}": ["type:drupal-custom-module"],
      "docroot/themes/custom/{$name}": ["type:drupal-custom-theme"],
      "drush/contrib/{$name}": ["type:drupal-drush"]
},
```

then cd to the folder then
composer install

**Comment by gordasgdc** [comment]
![varb](https://user-images.githubusercontent.com/35461429/38136154-e17d8680-341c-11e8-9b46-253e0f31e8a8.jpeg)

I move the composer.json file into a new folder 
I change "docroot" to "public_html" 
composer install and its make me "docroot" file and "public_html" file

**Comment by Natshah** [comment]
gordasgdc, Please test with a new testing folder

1. Create a new folder to test. /var/www/html/test
2. Changed directory with cd /var/www/html/test/
3. git clone --branch 8.4.18 git@github.com:Vardot/varbase-project.git test-project,
    or you could download and upzip https://github.com/Vardot/varbase-project/archive/8.4.18.zip to test-project in /var/www/html/test/
4. cd /var/www/html/test/test-project/
5. Edit the composer.json change "docroot" to "public_html"
6. cd /var/www/html/test/test-project/
7. composer install -vvv
8. chmod 775 -R /var/www/html/test/test-project/
9. chown www-data:{$user} -R /var/www/html/test/test-project/
10. Then go to your http://localhost/test/test-project/public_html .. or the domain which pointing at the /var/www/html/test/test-project/public_html

**Comment by gordasgdc** [comment]
Thank you ,great work
With php 7.0 and 7.2 it's not working ,only with PHP 7.1.
