### ISSUE TITLE
Upgrading from 8.6.x to 8.7.0 Question

### ISSUE THREAD

**Issue by jasonruyle** [Vardot/varbase#87]
When moving from version 6.x (dev release) to 7.0, I noticed that there were no new updates in the varbase update (update-helper). There were some new dependencies for currently installed modules on the site, that didn't get updated or applied.

Was this an error or is there something that needs to be done before moving from 6 to 7?

**Comment by Natshah** [comment]
Thank you  for the question, it is on the spot 

In Varbase 8.6.12
The default Varbase Project composer will look as in
https://github.com/Vardot/varbase-project/blob/8.6.12/composer.json

But the default Varbase project composer for Varbase 8.7.0 will look like
https://github.com/Vardot/varbase-project/blob/8.7.0/composer.json

You could do the editing with a **manual refactor upgrade** to make the jump from ~8.6.0 to ~8.7.0
copy - past - and bring back your required modules, or libraries then a composer update

Or You could use the **Varbase Updater** upgrade and refactor tool

**Updating a Varbase Site**
https://docs.varbase.vardot.com/updating-varbase

**OPTION 1: Automated Process — Using Varbase Updater**
https://docs.varbase.vardot.com/updating-varbase#option-1-automated-process-using-varbase-updater
This will do a **full automated refactor** for the composer and **full automated update** 

**OPTION 2: Manual Process — Do it Yourself**
https://docs.varbase.vardot.com/updating-varbase#option-2-manual-process-do-it-yourself
This will do semi-automated Refactor

```
composer varbase-refactor-composer
```

Then you could edit the composer after that and do the update your way

**Comment by jasonruyle** [comment]
Thanks for your response. I originally did it the manual way, but did not run the command:
`composer varbase-refactor-composer`
Instead comparing things manually and doing the updates through drush.

I'll see if the configuration changes are showing, it seemed to only show up to 6.12 on my end, after running composer update, drush updb, etc.
