### ISSUE TITLE
varbase_core_optional_update_8701

### ISSUE THREAD

**Issue by jasonruyle** [Vardot/varbase#88]
Reviewing code updates/changes and I'm running into some issues when going from the 8.7.0 version to 8.7.2 version. I don't always expect things to be perfectly smooth, we do modify things on our end and that's a given.  But looking over the varbase_core.install file I'm getting this error:

```
Variable $optional_install_path is undefined.
```
On line 343.

Is this something that was suppose to be defined somewhere else?

**Comment by Natshah** [comment]
Thanks Jason for reporting
**Issue #3089257: Fixed a Notice for Undefined variable: optional_install_path in varbase_core_optional_update_8701**
https://www.drupal.org/node/3089257

Quick fix release

Released varbase_core 8.x-7.4
https://www.drupal.org/project/varbase_core/releases/8.x-7.4
