### ISSUE TITLE
Setting up in Windows 10 with composer

### ISSUE THREAD

**Issue by mkgn** [Vardot/varbase#89]
This may not be a major issue but I thought to mention it here in case you need to address it. I am using Laragon with PHP 7.4.6, MariaDb 10.0.38 & Apache 2.4.43 in Windows 10.

When I run the composer to install to the end of it, gives below message;

Create a sites/default/settings.php file with chmod 0666
Create a sites/default/services.yml file with chmod 0666
> Varbase\composer\ScriptHandler::removeGitDirectories
Create a sites/default/files directory with chmod 0777
Script Varbase\composer\ScriptHandler::removeGitDirectories handling the post-install-cmd event terminated with an exception

[ErrorException]
  unlink(D:\WAMP\laragon\www\shoppa/docroot/modules/contrib/mail_edit/.git/objects/pack/pack-92d7d942673146b58a71ded2
  bbbdde12c26fb5c8.idx): Permission denied

However I am running as an administrator. If I do a vanilla D8 setup; it won't complain.

**Comment by Natshah** [comment]
Please try to Enable the Linux Bash Shell in Windows 10
https://www.laptopmag.com/articles/use-bash-shell-windows-10
Search for ways to set up the the composer to work with permissions or without permissions
