### ISSUE TITLE
composer install of 8.8.7 fails on patch #2869592

### ISSUE THREAD

**Issue by aDarkling** [Vardot/varbase#91]
Windows 10 command line
Installed via "composer create-project Vardot/varbase-project varbase01 --no-dev --no-interaction"

everything goes fine until...

  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2869592-remove-update-warning-7.patch (Issue #2869592: Disabled update module shouldn't produce a status report warning)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2869592-remove-update-warning-7.patch

  [Exception]
  Cannot apply patch Issue #2869592: Disabled update module shouldn't produce a status report warning (https://www.drupal.org/files/issues/2869592-
  remove-update-warning-7.patch)!

**Comment by Natshah** [comment]
Out dated
